### ISSUE TITLE
CUI? CLI?

### ISSUE THREAD

**Issue by jayallen** [hachiojipm/awesome-perl#41]
Just a clarification: In my 25 years of programming experience, I've never seen the acronym "CUI".  I'm assuming, based on Getopt::Long, that that section is for libraries that aid development of command-line run programs.  If so, you might consider using the common acronym "CLI" (command-line interface) to eliminate confusion.

**Comment by uzulla** [comment]
I agree.

**Comment by uzulla** [comment]
Thanks! fixed.
